"""add game  user association in model.py

Revision ID: b4393f5f2921
Revises: 7641d13bec78
Create Date: 2024-03-26 00:30:00.247590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4393f5f2921'
down_revision = '7641d13bec78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
